
export const CREATE_PLATAFORMA = 'CREATE_PLATAFORMA'
export const DELETE_PLATAFORMAS = 'DELETE_PLATAFORMAS'
export const FETCH_ALL_PLATAFORMAS = 'FETCH_ALL_PLATAFORMAS'
export const UPDATE_PLATAFORMA = 'UPDATE_PLATAFORMA'

export const CREATE_FAQ = 'CREATE_FAQ'
export const DELETE_FAQS = 'DELETE_FAQS'
export const FETCH_ALL_FAQS = 'FETCH_ALL_FAQS'
export const UPDATE_FAQ = 'UPDATE_FAQ'

export const CREATE_WPP = 'CREATE_WPP'
export const DELETE_WPPS = 'DELETE_WPPS'
export const FETCH_ALL_WPPS = 'FETCH_ALL_WPPS'
export const UPDATE_WPP = 'UPDATE_WPP'