
export const CREATE_PLATAFORMA = 'CREATE_PLATAFORMA'
export const DELETE_PLATAFORMAS = 'DELETE_PLATAFORMAS'
export const FETCH_ALL_PLATAFORMAS = 'FETCH_ALL_PLATAFORMAS'
export const UPDATE_PLATAFORMA = 'UPDATE_PLATAFORMA'